if gradCheckFlag
    
    % Compute numerical gradient
    argno = 1; [gWzfn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wzf,argno);
    argno = argno + 1; [gRzfn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rzf,argno);
    argno = argno + 1; [gbzfn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bzf,argno);
    
    argno = argno + 1; [gWifn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wif,argno);    
    argno = argno + 1; [gRifn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rif,argno);
    argno = argno + 1; [gpifn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,pif,argno);
    argno = argno + 1; [gbifn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bif,argno);
    
    argno = argno + 1; [gWffn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wff,argno);    
    argno = argno + 1; [gRffn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rff,argno);
    argno = argno + 1; [gpffn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,pff,argno);
    argno = argno + 1; [gbffn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bff,argno);
    
    argno = argno + 1; [gWofn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wof,argno);    
    argno = argno + 1; [gRofn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rof,argno);
    argno = argno + 1; [gpofn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,pof,argno);
    argno = argno + 1; [gbofn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bof,argno);
    
    argno = argno + 1; [gUfn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Uf,argno);
    

    argno = argno + 1; [gWzbn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wzb,argno);
    argno = argno + 1; [gRzbn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rzb,argno);
    argno = argno + 1; [gbzbn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bzb,argno);
    
    argno = argno + 1; [gWibn] = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wib,argno);    
    argno = argno + 1; [gRibn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rib,argno);
    argno = argno + 1; [gpibn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,pib,argno);
    argno = argno + 1; [gbibn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bib,argno);
    
    argno = argno + 1; [gWfbn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wfb,argno);    
    argno = argno + 1; [gRfbn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rfb,argno);
    argno = argno + 1; [gpfbn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,pfb,argno);
    argno = argno + 1; [gbfbn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bfb,argno);
    
    argno = argno + 1; [gWobn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Wob,argno);    
    argno = argno + 1; [gRobn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Rob,argno);
    argno = argno + 1; [gpobn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,pob,argno);
    argno = argno + 1; [gbobn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bob,argno);
    
    argno = argno + 1; [gUbn]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,Ub,argno);
    
    argno = argno + 1; [gbun]  = compute_NumericalGrad(Wzf,Rzf,bzf,Wif,Rif,pif,bif,Wff,Rff,pff,bff,Wof,Rof,pof,bof,Uf,...         
        Wzb,Rzb,bzb,Wib,Rib,pib,bib,Wfb,Rfb,pfb,bfb,Wob,Rob,pob,bob,Ub,...
        bu,X,Y,f,nl,sl,cfn,bu,argno);
    
    % Compute the difference between numerical and back-prop gradients
    [dgWzfn] = compute_gradDiff_fn(gWzfn,gWzf,'gWzf');
    [dgWifn] = compute_gradDiff_fn(gWifn,gWif,'gWif');
    [dgWffn] = compute_gradDiff_fn(gWffn,gWff,'gWff');
    [dgWofn] = compute_gradDiff_fn(gWofn,gWof,'gWof');
    
    [dgRzfn] = compute_gradDiff_fn(gRzfn,gRzf,'gRzf');
    [dgRifn] = compute_gradDiff_fn(gRifn,gRif,'gRif');
    [dgRffn] = compute_gradDiff_fn(gRffn,gRff,'gRff');
    [dgRofn] = compute_gradDiff_fn(gRofn,gRof,'gRof');
    
    [dgbzfn] = compute_gradDiff_fn(gbzfn,gbzf,'gbzf');
    [dgbifn] = compute_gradDiff_fn(gbifn,gbif,'gbif');
    [dgbffn] = compute_gradDiff_fn(gbffn,gbff,'gbff');
    [dgbofn] = compute_gradDiff_fn(gbofn,gbof,'gbof');
    
    [dgpifn] = compute_gradDiff_fn(gpifn,gpif,'gpif');
    [dgpffn] = compute_gradDiff_fn(gpffn,gpff,'gpff');
    [dgpofn] = compute_gradDiff_fn(gpofn,gpof,'gpof');
    
    [dgUfn] = compute_gradDiff_fn(gUfn,gUf,'gUf');
    
    
    [dgWzbn] = compute_gradDiff_fn(gWzbn,gWzb,'gWzb');
    [dgWibn] = compute_gradDiff_fn(gWibn,gWib,'gWib');
    [dgWfbn] = compute_gradDiff_fn(gWfbn,gWfb,'gWfb');
    [dgWobn] = compute_gradDiff_fn(gWobn,gWob,'gWob');
    
    [dgRzbn] = compute_gradDiff_fn(gRzbn,gRzb,'gRzb');
    [dgRibn] = compute_gradDiff_fn(gRibn,gRib,'gRib');
    [dgRfbn] = compute_gradDiff_fn(gRfbn,gRfb,'gRfb');
    [dgRobn] = compute_gradDiff_fn(gRobn,gRob,'gRob');
    
    [dgbzbn] = compute_gradDiff_fn(gbzbn,gbzb,'gbzb');
    [dgbibn] = compute_gradDiff_fn(gbibn,gbib,'gbib');
    [dgbfbn] = compute_gradDiff_fn(gbfbn,gbfb,'gbfb');
    [dgbobn] = compute_gradDiff_fn(gbobn,gbob,'gbob');
    
    [dgpibn] = compute_gradDiff_fn(gpibn,gpib,'gpib');
    [dgpfbn] = compute_gradDiff_fn(gpfbn,gpfb,'gpfb');
    [dgpobn] = compute_gradDiff_fn(gpobn,gpob,'gpob');
    
    [dgUbn] = compute_gradDiff_fn(gUbn,gUb,'gUb');
    
    [dgbun] = compute_gradDiff_fn(gbun,gbu,'gbu');
    
    pause
    
end